dubbo:
  application:
    name: provider-server
  registry:
    address: zookeeper://127.0.0.1:2181
    client: curator
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.ggz.service
  protocol:
    port: 20880

  provider:
    executes: 20
    actives: 20
    interface: com.ggz.service.TicketService
  consumer:
    actives: 20

server:
  port: 8081