dubbo:
  application:
    name: provider-server
  registry:
    address: zookeeper://127.0.0.1:2181
    client: curator
  metadata-report:
    address: zookeeper://127.0.0.1:2181
  scan:
    base-packages: com.ggz.service
  protocol:
    port: 20880

server:
  port: 8081