
spring:
  application:
    name: oauth2Client
  redis:
    database: 2
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8887
  forward-headers-strategy: native

security:
  oauth2:
    client:
      client-id: user-client
      client-secret: user-secret-8888
      user-authorization-uri: http://localhost:8888/oauth/authorize
      access-token-uri: http://localhost:8888/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8888/oauth/check_token

management:
  endpoint:
    health:
      enabled: true
