
spring:
  application:
    name: oauth2Client
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ccmessage?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&serverTimezone=GMT%2B8
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update #自动更新
    show-sql: true #日志中显示sql语句
  redis:
    database: 2
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8887
  forward-headers-strategy: native

security:
  oauth2:
    client:
      client-id: client_1
      client-secret: 123456
      user-authorization-uri: http://localhost:8888/oauth/authorize
      access-token-uri: http://localhost:8888/oauth/token
    resource:
      id: user-client
      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8888/oauth/check_token

management:
  endpoint:
    health:
      enabled: true
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace

