spring:
  application:
    name: openFeign
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8005

feign:
  hystrix:
    enabled: true


