spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://gitee.com/fzggz/springcloud
          searchPaths: spring-cloud-config-file
          timeout: 60
          username: 14702954341
          password: gitee9527...ggz
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/