spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/how2j/springcloudConfig
          searchPaths: respo
          proxy:
            host: 127.0.0.1
            port: 26673
            nonProxyHosts: localhost
          timeout: 60
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/