

spring:

  # thymeleaf 配置
  thymeleaf:
    cache: false
    encoding: UTF-8
    check-template-location: true
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  mvc:
    static-path-pattern: /**

  application:
    name: mainApp
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8004



