spring:
  application:
    name: openFeign
#  zipkin:
#    base-url: http://localhost:9411
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8005

feign:
  hystrix:
    enabled: true

security:
  oauth2:
    client:
      client-id: client_feign_1
      client-secret: 123456
      user-authorization-uri: http://localhost:8888/oauth/authorize
      access-token-uri: http://localhost:8888/oauth/token
#    resource:
#      id: user-client
#      user-info-uri: user-info
    authorization:
      check-token-access: http://localhost:8888/oauth/check_token



