#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  application:
    name: provider1
#  zipkin:
#    base-url: http://localhost:9411
#  rabbitmq:
#    host: 192.168.147.128
#    port: 5672
#    username: admin
#    password: 123

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1

dubbo:
  application:
    name: provider1
  registry:
    address: zookeeper://127.0.0.1:2181

#server:
#  port: 8007
