#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  application:
    name: oauthServer
  redis:
    database: 0
    host: localhost
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    timeout: 10000

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

server:
  port: 8888
  forward-headers-strategy: native

management:
  endpoint:
    health:
      enabled: true
